/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'INVENTORYAI',systemName:'知华智能库存优化平台',englishName:'AI INVENTORY OPTIMIZATION',theme:{primary:'#3f6a63',dark:'#243e3a',accent:'#cb8444'},workspace:'供应链中心 / 库存策略组',fieldWorkspace:'华东物流中心 / 库存分析组',period:'2026-08-19 · 滚动分析',liveText:'WMS 与需求数据于 10:38 更新',fieldContextLabel:'分析范围',fieldContext:'华东仓群 · 消费品',fieldUser:'林澈',fieldRole:'库存分析师',adminUser:'苏岚',adminRole:'供应链计划负责人',
 adminTitle:'库存健康运营中心',adminBreadcrumb:'供应链 / 智能库存',adminSubtitle:'连接库存、在途、需求、交期与效期数据，生成补货、持有、减量和处置建议。',exportAction:'导出库存报告',createAction:'新建分析任务',chartTitle:'库存健康改善趋势',chartSubtitle:'健康 SKU 比例 / 运营目标',chartLabels:['W27','W28','W29','W30','W31','W32','W33','W34','W35'],loadTitle:'仓群库存负荷',loadSubtitle:'异常 SKU 占分析能力',recordsTitle:'重点库存优化任务',recordsSubtitle:'按缺货、滞销、临期和资金占用排序',issueTitle:'库存风险事件',issueSubtitle:'需要采购、销售或财务共同决策',
 recordName:'库存任务',itemName:'商品组合',unitName:'库存团队',batchName:'分析策略',planName:'SKU',doneName:'已分析',exceptionName:'异常',unitLabel:'个',listBreadcrumb:'库存策略 / 优化任务',listSubtitle:'管理库存覆盖、安全库存、滞销与临期处置，记录算法建议和人工决策。',listSummary:[['分析 SKU','4,860'],['缺货风险','38'],['滞销临期','62',true],['健康库存','91.6%']],tabs:['全部','待分析','分析中','待审批','已归档'],
 fieldBreadcrumb:'库存工作台 / 华东仓群',fieldTitle:'库存优化工作台',fieldSubtitle:'待分析 18 项 · 缺货风险 5 项 · 滞销临期 9 项',fieldSecondary:'查看库存分布',reportAction:'提交库存意见',fieldNoticeTitle:'库存数据准备完成',fieldNotice:'WMS 对账一致率 99.4%',steps:['数据汇聚','健康诊断','动作建议','人工审批','效果复盘'],documentAction:'查看库存证据',printAction:'导出处置单',resourceCardTitle:'库存数据资源',resourceValueLabel:'今日计算量',resourceHealthLabel:'数据健康度',quickSubtitle:'常用库存入口',quickActions:[['库存反馈','/shopfloor/report','补货、减量与处置意见'],['商品组合','/shopfloor/material','库存、需求、交期和效期'],['数据资源','/shopfloor/resources','WMS、需求和效期服务'],['风险升级','/shopfloor/andon','重大缺货、滞销与报损']],
 reportDefaults:[8,1],reportTitle:'库存优化反馈',reportSubtitle:'记录采纳动作、调整数量和业务依据。',reportSuccess:'库存优化意见已提交',reportPlaceholder:'填写需求变化、库存原因、处置数量与审批依据',reportFootnote:'报损、清仓和重大采购调整必须经过授权审批',ruleTitle:'库存动作安全门禁',ruleSubtitle:'INVENTORY-AI · V1.0',rules:[['重大缺货','采购与销售确认'],['临期处置','质量部门复核'],['库存报损','财务审批'],['策略复盘','每周',true]],fieldTotals:[['18','待分析任务'],['5','缺货风险'],['9','滞销临期'],['99.4%','WMS 对账一致率']],
 adminMenus:[['/admin','home','库存运营中心'],['/admin/work-orders','order','优化任务'],['/admin/samples','box','商品组合'],['/admin/schedule','calendar','补货日历'],['/admin/methods','process','库存策略'],['/admin/reviews','quality','动作审批'],['/admin/resources','machine','数据资源'],['/admin/report','chart','库存分析']],fieldMenus:[['/shopfloor','home','库存工作台'],['/shopfloor/report','report','优化反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','商品组合'],['/shopfloor/resources','machine','数据状态'],['/shopfloor/andon','risk','风险升级',5]],moduleTitles:{tasks:['我的库存任务','查看风险、资金和处置时限'],material:['商品库存组合','查看库存、在途、需求、交期和效期'],resources:['库存数据中心','管理 WMS、需求与效期连接器'],andon:['库存风险升级','提交重大缺货、滞销与报损事件'],samples:['商品组合台账','维护商品层级、仓库和责任人'],schedule:['补货与处置日历','协调采购、促销和清仓窗口'],methods:['库存策略','维护覆盖天数、安全库存和处置规则'],reviews:['库存动作审批','记录采纳、调整和驳回意见'],report:['库存健康分析','分析周转、缺货、滞销和资金占用']},
 tagline:'让库存既能满足需求，也不沉淀过多资金',storyTitle:'从库存数字到经营动作，<br/>每条建议都能解释和复盘',storyText:'把补货、减量、临期和滞销放进同一套工作流，让供应链团队更早采取行动。',pattern:[2,5,8,11,14,17,20,23,26,29,31],loginStats:[['4,860','分析 SKU'],['91.6%','健康库存'],['62','滞销临期']],loginTitle:'库存健康运营中心',adminDemo:'库存 / 需求 / 周转',fieldDemo:'诊断 / 建议 / 处置'}
export const records=[{no:'IV-260819-118',name:'夏季风扇库存组合',code:'FAN-SUMMER',unit:'华东仓配组',group:'消费事业部',plan:186,done:142,exception:18,due:'08-19',batch:'季节+周转',status:'分析中',progress:76,priority:'关注'},{no:'IV-260819-112',name:'商用滤芯安全库存',code:'FILTER-B2B',unit:'库存策略中心',group:'大客户事业部',plan:96,done:64,exception:5,due:'08-20',batch:'交期+补货',status:'待分析',progress:67,priority:'正常'},{no:'IV-260819-106',name:'临期食品处置组合',code:'FOOD-EXPIRY',unit:'库存处置组',group:'零售事业部',plan:240,done:86,exception:32,due:'08-19',batch:'临期+滞销',status:'待审批',progress:36,priority:'紧急'},{no:'IV-260819-099',name:'清洁用品例行分析',code:'CLEAN-BASE',unit:'华东仓配组',group:'消费事业部',plan:168,done:168,exception:3,due:'08-18',batch:'稳定周转',status:'已归档',progress:100,priority:'正常'}]
export const resources=[{code:'WMS-01',name:'WMS 库存连接器',unit:'供应链数据组',status:'运行中',health:99,value:'4,860',valueUnit:'SKU',note:'库存于 10:30 完成对账'},{code:'DEMAND-02',name:'日均需求服务',unit:'计划算法组',status:'运行中',health:96,value:'91.6',valueUnit:'%',note:'需求覆盖保持稳定'},{code:'EXPIRY-03',name:'效期监控引擎',unit:'质量与库存组',status:'预警',health:89,value:'62',valueUnit:'SKU',note:'9 项将在 30 天内到期'}]
export const reviews=[{no:'RV-260819-032',title:'临期食品处置组合',type:'库存处置审批',detail:'涉及 240 个 SKU · 苏岚',result:'待确认'},{no:'RV-260819-027',title:'清洁用品例行分析',type:'健康复核',detail:'覆盖 68 天 · 林澈',result:'通过'},{no:'RV-260819-018',title:'夏季风扇库存组合',type:'滞销复核',detail:'覆盖升至 118 天',result:'异常'}]
export const adminMetrics=[['分析 SKU','4,860','覆盖 12 个仓库','blue'],['健康库存','91.6%','较上周 +1.2%','green'],['缺货风险','38','预计影响销售 56 万','orange'],['滞销临期','62','资金占用 430 万','red']]
export const fieldMetrics=[['我的任务','18','5 项缺货风险','blue'],['今日已分析','286','采纳率 78.4%','green'],['滞销临期','9','3 项今日到期','orange'],['对账一致率','99.4%','2 个仓库待确认','slate']]
export const chartActual=[82,84,85,86,87,88,89,91,92],chartTarget=[85,86,87,88,89,90,92,93,94]
export const loads=[['华东主仓',86,'异常 28 项'],['华南仓群',72,'异常 19 项'],['华北仓群',63,'异常 14 项'],['西南仓群',48,'异常 9 项']]
export const issues=[['临期','食品组合将在 30 天内集中到期','建议启动分级促销与调拨','待审批'],['缺货','商用滤芯库存低于交期需求','采购交期预计 12 天','处理中'],['滞销','夏季风扇覆盖升至 118 天','建议暂停后续采购','待决策']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
